# Generated by Django 4.1.3 on 2022-11-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_alter_message_options_remove_message_hash_bloks_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="hash_bloks",
            field=models.CharField(default=0, max_length=200),
        ),
    ]
