# Generated by Django 4.1.3 on 2022-11-25 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_message_hash_bloks"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.IntegerField(blank=True)),
                ("open_key", models.CharField(blank=True, max_length=100)),
                ("secret_key", models.CharField(blank=True, max_length=100)),
                ("aes_key", models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
