# Generated by Django 4.1.3 on 2022-11-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_alter_message_receiver_alter_message_sender"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="full_name_receiver",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Полное имя получателя",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="full_name_send",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Полное имя отправителя",
            ),
        ),
    ]
